# Generated by Django 2.2.2 on 2019-06-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(help_text='기억카드 key')),
                ('value', models.TextField(help_text='기억카드 value')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일자')),
                ('passed_at', models.PositiveIntegerField(default=0, help_text='마지막 기억 일시 (Epoch Timestamp)')),
                ('remind_after', models.PositiveIntegerField(default=0, help_text='n * 5000초 후 다시 기억')),
            ],
        ),
    ]
